version: "3"
services:
  app:
    image: node:16
    volumes:
      - ./:/code
    working_dir: /code
    env_file:
      - '.env'
    command: sh -c "test -d node_modules || npm install; npm run dev"
    ports:
      - "8999:3000"
    tty: true
